package com.ndjk.cl.wechat.dao;



import com.ndjk.cl.wechat.model.UserWechat;

import java.util.Map;

public interface UserWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_wechat
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_wechat
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    int insert(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_wechat
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    int insertSelective(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_wechat
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    UserWechat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_wechat
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    int updateByPrimaryKeySelective(UserWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_wechat
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    int updateByPrimaryKey(UserWechat record);

    UserWechat findSelective(Map<String, Object> param);
}