package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class ColumnList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_column_list.id
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_column_list.column_name
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_column_list.column_type
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    private String columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_column_list.create_time
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_column_list.update_time
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_column_list.id
     *
     * @return the value of nd_column_list.id
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_column_list.id
     *
     * @param id the value for nd_column_list.id
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_column_list.column_name
     *
     * @return the value of nd_column_list.column_name
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_column_list.column_name
     *
     * @param columnName the value for nd_column_list.column_name
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_column_list.column_type
     *
     * @return the value of nd_column_list.column_type
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_column_list.column_type
     *
     * @param columnType the value for nd_column_list.column_type
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType == null ? null : columnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_column_list.create_time
     *
     * @return the value of nd_column_list.create_time
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_column_list.create_time
     *
     * @param createTime the value for nd_column_list.create_time
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_column_list.update_time
     *
     * @return the value of nd_column_list.update_time
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_column_list.update_time
     *
     * @param updateTime the value for nd_column_list.update_time
     *
     * @mbggenerated Sun Jan 21 14:57:25 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}