package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class ContentManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.id
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.title
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.column_id
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Long columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.column_type
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private String columnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.author
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.picture_url
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private String pictureUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.other_url
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private String otherUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.thumbs_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Integer thumbsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.views_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Integer viewsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.collection_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Integer collectionNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.create_time
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.update_time
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_content_manage.contentes
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    private String contentes;

    private String contentType;

    private String columnIdStr;

    private String columnTypeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.id
     *
     * @return the value of nd_content_manage.id
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.id
     *
     * @param id the value for nd_content_manage.id
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.title
     *
     * @return the value of nd_content_manage.title
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.title
     *
     * @param title the value for nd_content_manage.title
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.column_id
     *
     * @return the value of nd_content_manage.column_id
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Long getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.column_id
     *
     * @param columnId the value for nd_content_manage.column_id
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setColumnId(Long columnId) {
        this.columnId = columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.column_type
     *
     * @return the value of nd_content_manage.column_type
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public String getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.column_type
     *
     * @param columnType the value for nd_content_manage.column_type
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setColumnType(String columnType) {
        this.columnType = columnType == null ? null : columnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.author
     *
     * @return the value of nd_content_manage.author
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.author
     *
     * @param author the value for nd_content_manage.author
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.picture_url
     *
     * @return the value of nd_content_manage.picture_url
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.picture_url
     *
     * @param pictureUrl the value for nd_content_manage.picture_url
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.other_url
     *
     * @return the value of nd_content_manage.other_url
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public String getOtherUrl() {
        return otherUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.other_url
     *
     * @param otherUrl the value for nd_content_manage.other_url
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setOtherUrl(String otherUrl) {
        this.otherUrl = otherUrl == null ? null : otherUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.thumbs_num
     *
     * @return the value of nd_content_manage.thumbs_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Integer getThumbsNum() {
        return thumbsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.thumbs_num
     *
     * @param thumbsNum the value for nd_content_manage.thumbs_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setThumbsNum(Integer thumbsNum) {
        this.thumbsNum = thumbsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.views_num
     *
     * @return the value of nd_content_manage.views_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Integer getViewsNum() {
        return viewsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.views_num
     *
     * @param viewsNum the value for nd_content_manage.views_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setViewsNum(Integer viewsNum) {
        this.viewsNum = viewsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.collection_num
     *
     * @return the value of nd_content_manage.collection_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Integer getCollectionNum() {
        return collectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.collection_num
     *
     * @param collectionNum the value for nd_content_manage.collection_num
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setCollectionNum(Integer collectionNum) {
        this.collectionNum = collectionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.create_time
     *
     * @return the value of nd_content_manage.create_time
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.create_time
     *
     * @param createTime the value for nd_content_manage.create_time
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.update_time
     *
     * @return the value of nd_content_manage.update_time
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.update_time
     *
     * @param updateTime the value for nd_content_manage.update_time
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_content_manage.contentes
     *
     * @return the value of nd_content_manage.contentes
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public String getContentes() {
        return contentes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_content_manage.contentes
     *
     * @param contentes the value for nd_content_manage.contentes
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    public void setContentes(String contentes) {
        this.contentes = contentes == null ? null : contentes.trim();
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getColumnIdStr() {
        return columnIdStr;
    }

    public void setColumnIdStr(String columnIdStr) {
        this.columnIdStr = columnIdStr;
    }

    public String getColumnTypeStr() {
        return columnTypeStr;
    }

    public void setColumnTypeStr(String columnTypeStr) {
        this.columnTypeStr = columnTypeStr;
    }
}