package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class ThumbsViewDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_detail.id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_detail.thumbs_id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    private Integer thumbsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_detail.user_id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_detail.openid
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_detail.ip
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_detail.create_time
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_detail.id
     *
     * @return the value of nd_thumbs_view_detail.id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_detail.id
     *
     * @param id the value for nd_thumbs_view_detail.id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_detail.thumbs_id
     *
     * @return the value of nd_thumbs_view_detail.thumbs_id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public Integer getThumbsId() {
        return thumbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_detail.thumbs_id
     *
     * @param thumbsId the value for nd_thumbs_view_detail.thumbs_id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public void setThumbsId(Integer thumbsId) {
        this.thumbsId = thumbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_detail.user_id
     *
     * @return the value of nd_thumbs_view_detail.user_id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_detail.user_id
     *
     * @param userId the value for nd_thumbs_view_detail.user_id
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_detail.openid
     *
     * @return the value of nd_thumbs_view_detail.openid
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_detail.openid
     *
     * @param openid the value for nd_thumbs_view_detail.openid
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_detail.ip
     *
     * @return the value of nd_thumbs_view_detail.ip
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_detail.ip
     *
     * @param ip the value for nd_thumbs_view_detail.ip
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_detail.create_time
     *
     * @return the value of nd_thumbs_view_detail.create_time
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_detail.create_time
     *
     * @param createTime the value for nd_thumbs_view_detail.create_time
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}