package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class ThumbsViewList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.id
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.name
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.thumbs_num
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private Integer thumbsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.view_num
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private Integer viewNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.is_del
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.ctime
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_thumbs_view_list.mtime
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.id
     *
     * @return the value of nd_thumbs_view_list.id
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.id
     *
     * @param id the value for nd_thumbs_view_list.id
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.name
     *
     * @return the value of nd_thumbs_view_list.name
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.name
     *
     * @param name the value for nd_thumbs_view_list.name
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.thumbs_num
     *
     * @return the value of nd_thumbs_view_list.thumbs_num
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public Integer getThumbsNum() {
        return thumbsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.thumbs_num
     *
     * @param thumbsNum the value for nd_thumbs_view_list.thumbs_num
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setThumbsNum(Integer thumbsNum) {
        this.thumbsNum = thumbsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.view_num
     *
     * @return the value of nd_thumbs_view_list.view_num
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public Integer getViewNum() {
        return viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.view_num
     *
     * @param viewNum the value for nd_thumbs_view_list.view_num
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setViewNum(Integer viewNum) {
        this.viewNum = viewNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.is_del
     *
     * @return the value of nd_thumbs_view_list.is_del
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.is_del
     *
     * @param isDel the value for nd_thumbs_view_list.is_del
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.ctime
     *
     * @return the value of nd_thumbs_view_list.ctime
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.ctime
     *
     * @param ctime the value for nd_thumbs_view_list.ctime
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_thumbs_view_list.mtime
     *
     * @return the value of nd_thumbs_view_list.mtime
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_thumbs_view_list.mtime
     *
     * @param mtime the value for nd_thumbs_view_list.mtime
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}