package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class VoteUse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_use.id
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_use.vid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_use.pid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_use.openid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_use.ip
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_use.ctime
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    private Date ctime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_use.id
     *
     * @return the value of nd_vote_use.id
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_use.id
     *
     * @param id the value for nd_vote_use.id
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_use.vid
     *
     * @return the value of nd_vote_use.vid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_use.vid
     *
     * @param vid the value for nd_vote_use.vid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_use.pid
     *
     * @return the value of nd_vote_use.pid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_use.pid
     *
     * @param pid the value for nd_vote_use.pid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_use.openid
     *
     * @return the value of nd_vote_use.openid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_use.openid
     *
     * @param openid the value for nd_vote_use.openid
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_use.ip
     *
     * @return the value of nd_vote_use.ip
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_use.ip
     *
     * @param ip the value for nd_vote_use.ip
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_use.ctime
     *
     * @return the value of nd_vote_use.ctime
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_use.ctime
     *
     * @param ctime the value for nd_vote_use.ctime
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }
}