package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class VotePlayer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.id
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.voteid
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private Integer voteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.pcode
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private String pcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.pname
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.pdesc
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private String pdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.votednum
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private Integer votednum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.is_del
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.ctime
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.mtime
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_player.photolist
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    private String photolist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.id
     *
     * @return the value of nd_vote_player.id
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.id
     *
     * @param id the value for nd_vote_player.id
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.voteid
     *
     * @return the value of nd_vote_player.voteid
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public Integer getVoteid() {
        return voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.voteid
     *
     * @param voteid the value for nd_vote_player.voteid
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setVoteid(Integer voteid) {
        this.voteid = voteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.pcode
     *
     * @return the value of nd_vote_player.pcode
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.pcode
     *
     * @param pcode the value for nd_vote_player.pcode
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setPcode(String pcode) {
        this.pcode = pcode == null ? null : pcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.pname
     *
     * @return the value of nd_vote_player.pname
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.pname
     *
     * @param pname the value for nd_vote_player.pname
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.pdesc
     *
     * @return the value of nd_vote_player.pdesc
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public String getPdesc() {
        return pdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.pdesc
     *
     * @param pdesc the value for nd_vote_player.pdesc
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setPdesc(String pdesc) {
        this.pdesc = pdesc == null ? null : pdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.votednum
     *
     * @return the value of nd_vote_player.votednum
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public Integer getVotednum() {
        return votednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.votednum
     *
     * @param votednum the value for nd_vote_player.votednum
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setVotednum(Integer votednum) {
        this.votednum = votednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.is_del
     *
     * @return the value of nd_vote_player.is_del
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.is_del
     *
     * @param isDel the value for nd_vote_player.is_del
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.ctime
     *
     * @return the value of nd_vote_player.ctime
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.ctime
     *
     * @param ctime the value for nd_vote_player.ctime
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.mtime
     *
     * @return the value of nd_vote_player.mtime
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.mtime
     *
     * @param mtime the value for nd_vote_player.mtime
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_player.photolist
     *
     * @return the value of nd_vote_player.photolist
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public String getPhotolist() {
        return photolist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_player.photolist
     *
     * @param photolist the value for nd_vote_player.photolist
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    public void setPhotolist(String photolist) {
        this.photolist = photolist == null ? null : photolist.trim();
    }
}