package com.ndjk.cl.brandinteraction.model;

import java.util.Date;

public class VoteList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.id
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.votename
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String votename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.pic
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.vdesc
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String vdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.date_s
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Date dateS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.date_e
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Date dateE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.status
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.is_del
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.votetype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String votetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.votenum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Integer votenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.showtype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String showtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.wxtype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private String wxtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.playernum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Integer playernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.votednum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Integer votednum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.reqnum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Integer reqnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.ctime
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_vote_list.mtime
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.id
     *
     * @return the value of nd_vote_list.id
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.id
     *
     * @param id the value for nd_vote_list.id
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.votename
     *
     * @return the value of nd_vote_list.votename
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getVotename() {
        return votename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.votename
     *
     * @param votename the value for nd_vote_list.votename
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setVotename(String votename) {
        this.votename = votename == null ? null : votename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.pic
     *
     * @return the value of nd_vote_list.pic
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.pic
     *
     * @param pic the value for nd_vote_list.pic
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.vdesc
     *
     * @return the value of nd_vote_list.vdesc
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getVdesc() {
        return vdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.vdesc
     *
     * @param vdesc the value for nd_vote_list.vdesc
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setVdesc(String vdesc) {
        this.vdesc = vdesc == null ? null : vdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.date_s
     *
     * @return the value of nd_vote_list.date_s
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Date getDateS() {
        return dateS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.date_s
     *
     * @param dateS the value for nd_vote_list.date_s
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setDateS(Date dateS) {
        this.dateS = dateS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.date_e
     *
     * @return the value of nd_vote_list.date_e
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Date getDateE() {
        return dateE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.date_e
     *
     * @param dateE the value for nd_vote_list.date_e
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setDateE(Date dateE) {
        this.dateE = dateE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.status
     *
     * @return the value of nd_vote_list.status
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.status
     *
     * @param status the value for nd_vote_list.status
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.is_del
     *
     * @return the value of nd_vote_list.is_del
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.is_del
     *
     * @param isDel the value for nd_vote_list.is_del
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.votetype
     *
     * @return the value of nd_vote_list.votetype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getVotetype() {
        return votetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.votetype
     *
     * @param votetype the value for nd_vote_list.votetype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setVotetype(String votetype) {
        this.votetype = votetype == null ? null : votetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.votenum
     *
     * @return the value of nd_vote_list.votenum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Integer getVotenum() {
        return votenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.votenum
     *
     * @param votenum the value for nd_vote_list.votenum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setVotenum(Integer votenum) {
        this.votenum = votenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.showtype
     *
     * @return the value of nd_vote_list.showtype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getShowtype() {
        return showtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.showtype
     *
     * @param showtype the value for nd_vote_list.showtype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setShowtype(String showtype) {
        this.showtype = showtype == null ? null : showtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.wxtype
     *
     * @return the value of nd_vote_list.wxtype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public String getWxtype() {
        return wxtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.wxtype
     *
     * @param wxtype the value for nd_vote_list.wxtype
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setWxtype(String wxtype) {
        this.wxtype = wxtype == null ? null : wxtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.playernum
     *
     * @return the value of nd_vote_list.playernum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Integer getPlayernum() {
        return playernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.playernum
     *
     * @param playernum the value for nd_vote_list.playernum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setPlayernum(Integer playernum) {
        this.playernum = playernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.votednum
     *
     * @return the value of nd_vote_list.votednum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Integer getVotednum() {
        return votednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.votednum
     *
     * @param votednum the value for nd_vote_list.votednum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setVotednum(Integer votednum) {
        this.votednum = votednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.reqnum
     *
     * @return the value of nd_vote_list.reqnum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Integer getReqnum() {
        return reqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.reqnum
     *
     * @param reqnum the value for nd_vote_list.reqnum
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setReqnum(Integer reqnum) {
        this.reqnum = reqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.ctime
     *
     * @return the value of nd_vote_list.ctime
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.ctime
     *
     * @param ctime the value for nd_vote_list.ctime
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_vote_list.mtime
     *
     * @return the value of nd_vote_list.mtime
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_vote_list.mtime
     *
     * @param mtime the value for nd_vote_list.mtime
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}