package com.ndjk.cl.user.model;

import java.util.Date;

public class UserOperatorLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_operator_log.id
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_operator_log.user_id
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_operator_log.contentes
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    private String contentes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_operator_log.login_time
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_operator_log.ip
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_operator_log.id
     *
     * @return the value of sys_user_operator_log.id
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_operator_log.id
     *
     * @param id the value for sys_user_operator_log.id
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_operator_log.user_id
     *
     * @return the value of sys_user_operator_log.user_id
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_operator_log.user_id
     *
     * @param userId the value for sys_user_operator_log.user_id
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_operator_log.contentes
     *
     * @return the value of sys_user_operator_log.contentes
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public String getContentes() {
        return contentes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_operator_log.contentes
     *
     * @param contentes the value for sys_user_operator_log.contentes
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public void setContentes(String contentes) {
        this.contentes = contentes == null ? null : contentes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_operator_log.login_time
     *
     * @return the value of sys_user_operator_log.login_time
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_operator_log.login_time
     *
     * @param loginTime the value for sys_user_operator_log.login_time
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_operator_log.ip
     *
     * @return the value of sys_user_operator_log.ip
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_operator_log.ip
     *
     * @param ip the value for sys_user_operator_log.ip
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}