package com.ndjk.cl.sys.model;

import java.util.Date;

public class SysAppConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.id
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.name
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.code
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.level
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.status
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.type
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.show_link
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private String showLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.point_link
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private String pointLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.remark
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.create_time
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nd_sys_app_config.update_time
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.id
     *
     * @return the value of nd_sys_app_config.id
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.id
     *
     * @param id the value for nd_sys_app_config.id
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.name
     *
     * @return the value of nd_sys_app_config.name
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.name
     *
     * @param name the value for nd_sys_app_config.name
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.code
     *
     * @return the value of nd_sys_app_config.code
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.code
     *
     * @param code the value for nd_sys_app_config.code
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.level
     *
     * @return the value of nd_sys_app_config.level
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.level
     *
     * @param level the value for nd_sys_app_config.level
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.status
     *
     * @return the value of nd_sys_app_config.status
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.status
     *
     * @param status the value for nd_sys_app_config.status
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.type
     *
     * @return the value of nd_sys_app_config.type
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.type
     *
     * @param type the value for nd_sys_app_config.type
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.show_link
     *
     * @return the value of nd_sys_app_config.show_link
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public String getShowLink() {
        return showLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.show_link
     *
     * @param showLink the value for nd_sys_app_config.show_link
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setShowLink(String showLink) {
        this.showLink = showLink == null ? null : showLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.point_link
     *
     * @return the value of nd_sys_app_config.point_link
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public String getPointLink() {
        return pointLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.point_link
     *
     * @param pointLink the value for nd_sys_app_config.point_link
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setPointLink(String pointLink) {
        this.pointLink = pointLink == null ? null : pointLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.remark
     *
     * @return the value of nd_sys_app_config.remark
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.remark
     *
     * @param remark the value for nd_sys_app_config.remark
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.create_time
     *
     * @return the value of nd_sys_app_config.create_time
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.create_time
     *
     * @param createTime the value for nd_sys_app_config.create_time
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nd_sys_app_config.update_time
     *
     * @return the value of nd_sys_app_config.update_time
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nd_sys_app_config.update_time
     *
     * @param updateTime the value for nd_sys_app_config.update_time
     *
     * @mbggenerated Fri Jan 12 10:34:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}