package com.ndjk.cl.user.dao;


import com.ndjk.cl.brandservice.model.SysUser;
import com.ndjk.cl.user.model.UserOperatorLog;

import java.util.List;

public interface UserOperatorLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_operator_log
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_operator_log
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    int insert(UserOperatorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_operator_log
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    int insertSelective(UserOperatorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_operator_log
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    UserOperatorLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_operator_log
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    int updateByPrimaryKeySelective(UserOperatorLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_operator_log
     *
     * @mbggenerated Tue Jan 30 17:45:53 CST 2018
     */
    int updateByPrimaryKey(UserOperatorLog record);

    //用户日志列表
    List<UserOperatorLog> listAll(UserOperatorLog userOperatorLog, int currentPage, int pageSize);
}