package com.ndjk.cl.wechat.model;

import java.util.Date;

public class UserWechat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.id
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.phone
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.open_id
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.create_time
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.nickname
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.sex
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.province
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.city
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.country
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.headimgurl
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.privilege
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String privilege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_wechat.unionid
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    private String unionid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.id
     *
     * @return the value of cl_user_wechat.id
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.id
     *
     * @param id the value for cl_user_wechat.id
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.phone
     *
     * @return the value of cl_user_wechat.phone
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.phone
     *
     * @param phone the value for cl_user_wechat.phone
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.open_id
     *
     * @return the value of cl_user_wechat.open_id
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.open_id
     *
     * @param openId the value for cl_user_wechat.open_id
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.create_time
     *
     * @return the value of cl_user_wechat.create_time
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.create_time
     *
     * @param createTime the value for cl_user_wechat.create_time
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.nickname
     *
     * @return the value of cl_user_wechat.nickname
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.nickname
     *
     * @param nickname the value for cl_user_wechat.nickname
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.sex
     *
     * @return the value of cl_user_wechat.sex
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.sex
     *
     * @param sex the value for cl_user_wechat.sex
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.province
     *
     * @return the value of cl_user_wechat.province
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.province
     *
     * @param province the value for cl_user_wechat.province
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.city
     *
     * @return the value of cl_user_wechat.city
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.city
     *
     * @param city the value for cl_user_wechat.city
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.country
     *
     * @return the value of cl_user_wechat.country
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.country
     *
     * @param country the value for cl_user_wechat.country
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.headimgurl
     *
     * @return the value of cl_user_wechat.headimgurl
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.headimgurl
     *
     * @param headimgurl the value for cl_user_wechat.headimgurl
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.privilege
     *
     * @return the value of cl_user_wechat.privilege
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.privilege
     *
     * @param privilege the value for cl_user_wechat.privilege
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setPrivilege(String privilege) {
        this.privilege = privilege == null ? null : privilege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_wechat.unionid
     *
     * @return the value of cl_user_wechat.unionid
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_wechat.unionid
     *
     * @param unionid the value for cl_user_wechat.unionid
     *
     * @mbggenerated Fri Jan 19 10:42:32 CST 2018
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }
}