package com.ndjk.cl.brandinteraction.dao;


import com.ndjk.cl.brandinteraction.model.ContentManage;
import com.ndjk.cl.brandinteraction.model.VotePlayer;
import com.ndjk.cl.brandinteraction.model.vo.ContentManageVo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;
@Repository
public interface ContentManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    int insert(ContentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    int insertSelective(ContentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    ContentManage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    int updateByPrimaryKeySelective(ContentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ContentManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_content_manage
     *
     * @mbggenerated Sun Jan 21 11:36:08 CST 2018
     */
    int updateByPrimaryKey(ContentManage record);

    List<ContentManage> listAll(ContentManageVo contentManageVo, @Param("offset") int offset, @Param("pageSize") int pageSiz);
}