package com.ndjk.cl.brandinteraction.dao;

import com.ndjk.cl.brandinteraction.model.ThumbsViewList;

public interface ThumbsViewListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_list
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_list
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    int insert(ThumbsViewList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_list
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    int insertSelective(ThumbsViewList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_list
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    ThumbsViewList selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_list
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    int updateByPrimaryKeySelective(ThumbsViewList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_list
     *
     * @mbggenerated Fri Jan 12 15:45:56 CST 2018
     */
    int updateByPrimaryKey(ThumbsViewList record);
}