package com.ndjk.cl.brandinteraction.dao;


import com.ndjk.cl.brandinteraction.model.ThumbsViewDetail;

public interface ThumbsViewDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_detail
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_detail
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    int insert(ThumbsViewDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_detail
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    int insertSelective(ThumbsViewDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_detail
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    ThumbsViewDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_detail
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    int updateByPrimaryKeySelective(ThumbsViewDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_thumbs_view_detail
     *
     * @mbggenerated Fri Jan 12 16:09:45 CST 2018
     */
    int updateByPrimaryKey(ThumbsViewDetail record);

    ThumbsViewDetail findThumbsViewDetailByOpenId(String openid);
}