package com.ndjk.cl.brandinteraction.dao;


import com.ndjk.cl.brandinteraction.model.VoteUse;

public interface VoteUseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_use
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_use
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    int insert(VoteUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_use
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    int insertSelective(VoteUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_use
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    VoteUse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_use
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    int updateByPrimaryKeySelective(VoteUse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_use
     *
     * @mbggenerated Mon Jan 15 14:19:58 CST 2018
     */
    int updateByPrimaryKey(VoteUse record);
}