package com.ndjk.cl.brandinteraction.dao;

import com.ndjk.cl.brandinteraction.model.VotePlayer;

import java.util.List;

public interface VotePlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    int insert(VotePlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    int insertSelective(VotePlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    VotePlayer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    int updateByPrimaryKeySelective(VotePlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(VotePlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_player
     *
     * @mbggenerated Mon Jan 15 14:17:01 CST 2018
     */
    int updateByPrimaryKey(VotePlayer record);

    List<VotePlayer> listAll();
}