package com.ndjk.cl.brandinteraction.dao;


import com.ndjk.cl.brandinteraction.model.VoteList;

public interface VoteListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_list
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_list
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    int insert(VoteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_list
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    int insertSelective(VoteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_list
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    VoteList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_list
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    int updateByPrimaryKeySelective(VoteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nd_vote_list
     *
     * @mbggenerated Mon Jan 15 14:13:29 CST 2018
     */
    int updateByPrimaryKey(VoteList record);
}